; Example applications demonstrating ocgtk

(executable
 (name counter_simple)
 (modules counter_simple)
 (libraries ocgtk.gtk))

(executable
 (name demo_all)
 (modules demo_all)
 (libraries ocgtk.gtk))

(executable
 (name counter)
 (modules counter)
 (libraries ocgtk.gtk ocgtk.gio))

(executable
 (name settings_panel)
 (modules settings_panel)
 (libraries ocgtk.gtk))

(executable
 (name text_editor)
 (modules text_editor)
 (libraries ocgtk.gtk))

(executable
 (name login_form)
 (modules login_form)
 (libraries ocgtk.gtk))

(executable
 (name form_example)
 (modules form_example)
 (libraries ocgtk.common ocgtk.gtk ocgtk.gdk))

(executable
 (name picture_test)
 (modules picture_test)
 (libraries ocgtk.gtk ocgtk.gdk ocgtk.common))
