(** Ownership tests for *generated* object-typed property getters.

    Unlike the method-return path (which emits [g_object_ref_sink(result)] for
    transfer-none GObject returns), the property-getter path generated by
    [gir_gen]'s [c_stub_gvalue.ml] [gen_object] case emits:

    {[
      prop_value = g_value_get_object (&prop_gvalue);
      result = Val_GtkAdjustment (prop_value);
      g_value_unset (&prop_gvalue);
    ]}

    [g_value_get_object] is transfer none (docs.gtk.org: "The returned data is
    owned by the instance" — the instance being the GValue), and the [Val_*]
    wrappers ([ml_gobject_val_of_ext]) register a finalizer that unconditionally
    [g_object_unref]s. So the only reference in play is the GValue's own, which
    [g_object_get_property] created ("a copy is made of the property contents
    and the caller is responsible for freeing the memory by calling
    g_value_unset()") and [g_value_unset] immediately releases. The wrapper
    therefore finalizes with an unref that has no matching ref of its own: a
    reference is stolen from the property's owner.

    These tests replicate that negative reference count by observing
    [Gobject.get_ref_count] deltas on an object whose property-owner (the
    renderer's "adjustment" property) is not the only owner — the test holds its
    own reference via [Adjustment.new_], which keeps the object alive for the
    duration of the assertions even while the buggy path undercounts it:

    - after the getter returns, the object must be at baseline + 1: the getter
      must have taken an owned reference before [g_value_unset] dropped the
      GValue's
    - after the wrapper is collected, the finalizer must release exactly that
      one reference, returning to baseline — never below it *)

open Alcotest
open Ocgtk_gtk.Gtk
module Adjustment = Wrappers.Adjustment
module Cell_renderer_spin = Wrappers.Cell_renderer_spin

let require_gtk = Gtk_test_helpers.require_gtk
let rc obj = Gobject.get_ref_count obj

(** Custom-block finalizers run during major collections. A second cycle covers
    values kept alive by the first cycle's allocations. *)
let collect () =
  Gc.full_major ();
  Gc.full_major ()

let check_rc label expected obj = check int label expected (rc obj)

(** [Cell_renderer_spin.get_adjustment] goes through the generated
    property-getter path. The adjustment is owned by both this test (via its own
    wrapper) and the renderer's "adjustment" property. *)
let test_property_getter_takes_owned_reference () =
  let spin = Cell_renderer_spin.new_ () in
  let adj = Adjustment.new_ 0.0 0.0 100.0 1.0 10.0 0.0 in
  let base = rc adj in
  Cell_renderer_spin.set_adjustment spin adj;
  check_rc "property setter gave the property its own reference" (base + 1) adj;
  let scoped () =
    let fetched = Cell_renderer_spin.get_adjustment spin in
    check bool "getter returns the same adjustment" true
      (Gobject.same fetched adj);
    (* The fetched wrapper is alive here, so the getter must hold an owned
       reference of its own on top of the property's and the test's.
       With the bug this reads [base + 1 - 1]: [g_value_unset] already
       released the only reference the wrapper will ever unref. *)
    check_rc "getter took an owned reference (transfer none honored)" (base + 2)
      adj
  in
  scoped ();
  collect ();
  check_rc "wrapper finalizer released exactly one reference" (base + 1) adj;
  (* The regression the stolen reference causes: the property owner's
     reference is consumed by the wrapper finalizer, so the renderer is left
     holding a dangling pointer. The adjustment must still be usable and the
     renderer must still own a live reference. The renderer is kept alive
     past the collection — its last use below — so its property reference is
     deterministically still counted here. *)
  check_rc "renderer's property reference still intact" (base + 1) adj;
  check (float 0.0) "adjustment still readable after wrapper GC" 0.0
    (Adjustment.get_value adj);
  check (float 0.0) "renderer still functional after wrapper GC" 0.0
    (Cell_renderer_spin.get_climb_rate spin)

let () =
  Alcotest.run "Generated property getter object ownership"
    [
      ( "transfer semantics",
        [
          Alcotest.test_case "property getter takes an owned reference" `Quick
            (require_gtk test_property_getter_takes_owned_reference);
        ] );
    ]
